### PR TITLE
feat(comments): add the component - INNO-342

### PR DESCRIPTION
**Pull request by kalinchernev**
Having `display: none` is questionable. In the midst of checking with back-end devs if some parts could be removed via templates or preprocessing.

### CODE REVIEW

**Comment by emeryro** [comment]
Global review:
- Author and date of the comment aren't located in same position as on the mockup. Is it a technical limitation?
- Icons for attached files aren't displayed, but I assume that it is because it is hosted directly on Farnet site. Maybe we should use an icon provided by the styleguide instead, so that it will be displayed correctly everywhere.
- Is there a reason why comment only takes half of the box in large screen (col-lg-6)?
- We should add the icon for the "Reply" link (using ::before css selector)
- On chrome, there is 1px between the blue arrow and comment box. Maybe we could just display it 1px lower. 
- Maybe put some lorem ipsum as example instead of random text (and also change author name to something generic).
- Text in readme file has to be updated (still displaying "not implemented yet")

**Comment by kalinchernev** [comment]
Hi @emeryro 

The current implementation is based on the realistic [markup provided from the website](https://webgate.acceptance.ec.europa.eu/multisite/farnet/community/it-support/discussion/discussion-it-support).

> Author and date of the comment aren't located in same position as on the mockup. Is it a technical limitation?

At the moment I did not modify the positioning for 2 reasons:
- hoping for updates in drupal template
- not going for relative/absolute positioning when drupal template can solve this better

Do you prefer that I go for relative/absolute positioning fixes around without template handling this?

> Icons for attached files aren't displayed, but I assume that it is because it is hosted directly on Farnet site. Maybe we should use an icon provided by the styleguide instead, so that it will be displayed correctly everywhere.

Indeed, was relying on something coming from the website, trying not to make things hard for the drupal developers.

I will rework this to be style-guide driven so that drupal developers follow this change on their side.

> Is there a reason why comment only takes half of the box in large screen (col-lg-6)?

All these layout rules are coming from the website. What is your suggestion to handle these?

> We should add the icon for the "Reply" link (using ::before css selector)

Sure, will update.

> On chrome, there is 1px between the blue arrow and comment box. Maybe we could just display it 1px lower.

Could you please add a screenshot about this?

> Maybe put some lorem ipsum as example instead of random text (and also change author name to something generic).

Ok, will do.

> Text in readme file has to be updated (still displaying "not implemented yet")

Will update.

**Comment by emeryro** [comment]
**1-** I will see with the developpers if they started to work on the update of the template.

**2-** I think you can rely on the class "file" (and everything below it) to add icon automatically instead of picture, so developpers won't have to update it on their side

**3-** Ok, the display issue comes from margin added on class "comment__actions". The issue is that the white border doesn't go full width, and content is on 2 lines (author isn't on the same line). Maybe you can try to alter class "comment-links" instead?
image

**5-** image

Thanks!

**Comment by kalinchernev** [comment]
Hi @emeryro 
An update was just pushed, these are updated:
- file (icon used)
- author (markup changed)
- reply icon
- example texts

**Comment by emeryro** [comment]
Thanks, I will check.
I just discussed with Cyril, they will start working on comment's template.
I think we should wait for their update before closing this task

**Comment by kalinchernev** [comment]
@emeryro sure, I believe further updates will be necessary after change in Drupal side. (Probably removing some of the styles)
If this will be helpful for @champcy and drupal devs:
- this is the change of [markup for the file](https://github.com/ec-europa/farnet-styleguide/pull/96/commits/02523db60ab78e9ae6e5875b5ba0ed2052c8e3de)
- this is the change for the [comment author moving up](https://github.com/ec-europa/farnet-styleguide/pull/96/commits/57c43122f5a59c0189fb774e1f657e2ff8dc1f49)

I'm available to adapt things

**Comment by kalinchernev** [comment]
WIP => will soon be reworked

**Comment by kalinchernev** [comment]
@emeryro this pull request is updated to the latest markup, so you can have a look again.
Please also open the email communication around this, as there's 1 difference in the provided markup -> the `comment` class which is meant to be the wrapper actually wraps the title, content, etc.

**Pull request merged**
