### PR TITLE
feat(community members): add component - INNO-372

### PR DESCRIPTION
**Pull request by kalinchernev**
Initially I started with custom classes, but then I noticed [it's a View](https://webgate.acceptance.ec.europa.eu/multisite/farnet/community/it-support/members_en).
In the view, it's surely possible to strip down things to this already existing bootstrap component.

### CODE REVIEW

**Comment by kalinchernev** [comment]
This pull request will have to be reworked completely => WIP

**Comment by kalinchernev** [comment]
@emeryro ready for validation.

**Comment by kalinchernev** [comment]
@emeryro changes made, hopefully it's a bit better.

**Comment by emeryro** [comment]
It's almost good; just make sure to update code in the different components (basic profile, community-member and community-members), as there are some differencies right now concerning font weight and image size.

**Comment by kalinchernev** [comment]
@emeryro sorry for missing this, all updated to the same columns and using the helper class for bold.

**Pull request merged**
